---
- hosts: all
  user: vagrant
  gather_facts: False 
  sudo: yes
  vars:
    - install_root: /vagrant
    - source_root: /vagrant
  tasks:
#    - name: Install Phabricator
#      shell: source /vagrant/install_rhel-derivs.sh
     - name: make repo path
       file: state=directory dest=/home/vagrant/repo
     - name: configure repo path
       lineinfile: dest="/vagrant/phabricator/conf/default.conf.php" state=present regexp="'repository.default-local-path' => *" line="'repository.default-local-path' => '/home/vagrant/repo',"


