---
- hosts: all
  user: vagrant
  gather_facts: False 
  sudo: yes
  vars:
    - install_root: /home/vagrant
  tasks:
#     - name: enable EPEL
#       shell: rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
     - yum: pkg={{ item }}
       with_items:
        - python-setuptools # ReviewBoard prerequisite
        - python-devel.i686 # ReviewBoard prerequisite
        - ReviewBoard  # Hey, it's a package!
        - sqlite.x86_64 # Cheapo database for now.
        - memcached # Recommended for speed.
        - python-memcached # Recommended for speed.
        - patch # Required for ReviewBoard's diff viewer.
        - git-core # Needed to communicate with Git
        - httpd.x86_64 # It is nice to have a web interface.
        - mod_wsgi.x86_64
     #- name: disable selinux # Ansible copy command fails, otherwise.
     #  selinux: state=disabled
